[package]
name = "aurora_cli"
version = "1.0.0"
edition = "2024"
description = "CLI utilities for validating Aurora models and generating documentation"
license = "MIT-or-Apache-2.0"

[package.metadata]
app_id = "org.crystultima.aurora_cli"

[[bin]]
name = "aurora_cli"
path = "src/main.rs"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
fern = { workspace = true }
indexmap = { workspace = true }
jsonschema = { workspace = true }
log = { workspace = true }
pathdiff = { workspace = true }
percent-encoding = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
whoami = { workspace = true }
