[package]
name = "aurora_cli"
description = "Aurora command-line interface"
edition = { workspace = true }
version = "1.0.0"
repository = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "aurora_cli"
path = "src/main.rs"

[package.metadata]
app_id = "org.crystultima.aurora.cli"

[dependencies]
aurora_shared = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
jsonschema = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3.10"

[lints]
workspace = true
