[package]
name = "aurora-tauri"
version = "1.0.0"
edition = "2024"

[[bin]]
name = "aurora"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
env_logger = { workspace = true }
jsonschema = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tauri = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
