excessive-nesting-threshold = 3
too-many-lines-threshold = 50
module-item-order-groupings = [
	[
		"modules",
		[
			"extern_crate",
			"mod",
			"foreign_mod",
		],
	],
	[
		"use",
		[
			"use",
		],
	],
	[
		"UPPER_SNAKE_CASE",
		[
			"static",
			"const",
		],
	],
	[
		"macros",
		[
			"macro",
		],
	],
	[
		"global_asm",
		[
			"global_asm",
		],
	],
	[
		"PascalCase",
		[
			"trait",
			"trait_alias",
			"ty_alias",
			"struct",
			"impl",
			"enum",
			"union",
		],
	],
	[
		"lower_snake_case",
		[
			"fn",
		],
	],
]
source-item-ordering = ["impl", "module", "struct", "trait"]
