//! Icon glyph mappings for Lucide-style names used in Card_Definitions.md.

pub(super) fn icon_glyph(icon_name: &str) -> Option<&'static str> {
	let normalized = icon_name.trim().to_ascii_lowercase();
	match normalized.as_str() {
		"target" => Some("🎯"),
		"compass" => Some("🧭"),
		"checklist" => Some("☑️"),
		"spark" => Some("✨"),
		"star" => Some("⭐"),
		"layers" => Some("🧱"),
		"app-window" => Some("🪟"),
		"cube" => Some("🧊"),
		"plug" => Some("🔌"),
		"file-text" => Some("📄"),
		"file" => Some("📁"),
		"shield-key" => Some("🛡️"),
		"database" => Some("🗄️"),
		"cloud" => Some("☁️"),
		"server" => Some("🖥️"),
		"server-cog" => Some("🖥️⚙️"),
		"workflow" => Some("🔁"),
		"steps" => Some("👣"),
		"user" => Some("👤"),
		"book" => Some("📖"),
		"bolt" => Some("⚡"),
		"timeline" => Some("🕒"),
		"dot" => Some("●"),
		"split" => Some("🔀"),
		"lock" => Some("🔒"),
		"ruler" => Some("📏"),
		"alert-triangle" => Some("⚠️"),
		"bug" => Some("🐛"),
		"beaker" => Some("🧪"),
		"note-sticky" => Some("🗒️"),
		"braces" => Some("🧩"),
		"square-dashed" => Some("⬚"),
		"question" => Some("❓"),
		_ => None,
	}
}
