pub struct CardDefinition {
	pub card_type: &'static str,
	pub acronym: &'static str,
	pub shape: &'static str,
	pub icon: &'static str,
	pub description: &'static str,
	pub fill: &'static str,
	pub color: &'static str,
}

impl CardDefinition {
	pub fn try_get_by_type(card_type: &str) -> Option<&'static CardDefinition> {
		Self::DEFINITIONS
			.iter()
			.find(|def| def.card_type == card_type)
	}

	pub fn try_get_by_acronym(acronym: &str) -> Option<&'static CardDefinition> {
		Self::DEFINITIONS.iter().find(|def| def.acronym == acronym)
	}

	pub fn get_all() -> &'static [CardDefinition] {
		Self::DEFINITIONS
	}

	pub fn get_groups() -> Vec<(&'static str, Vec<&'static str>)> {
		Self::GROUPS
			.iter()
			.map(|(name, acronyms)| (*name, acronyms.to_vec()))
			.collect::<Vec<(&'static str, Vec<&'static str>)>>()
	}
}

impl CardDefinition {
	const DEFINITIONS: &[CardDefinition] = &[
		CardDefinition {
			card_type: "Actor",
			acronym: "ACT",
			shape: "ellipse",
			icon: "user",
			description: "External role interacting with or obligating the system.",
			fill: "#1a2e05",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Trigger",
			acronym: "TRG",
			shape: "hexagon",
			icon: "alarm",
			description: "Event or condition initiating a process or action.",
			fill: "#78350f",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "ADR",
			acronym: "ADR",
			shape: "note",
			icon: "file-text",
			description: "Architectural Decision Record capturing a significant decision, alternatives considered, rationale, trade-offs, and consequences.",
			fill: "#1f2937",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Application",
			acronym: "APP",
			shape: "component",
			icon: "app-window",
			description: "Deployable software system implementing features.",
			fill: "#1e3a8a",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Artifact",
			acronym: "ART",
			shape: "tab",
			icon: "file",
			description: "Concrete work product produced or consumed by the system.",
			fill: "#1e293b",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Asset",
			acronym: "AST",
			shape: "box",
			icon: "shield-key",
			description: "Valuable information/resources requiring protection.",
			fill: "#334155",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Boundary",
			acronym: "BND",
			shape: "cluster (dashed)",
			icon: "square-dashed",
			description: "Logical grouping of other cards; `End` subtype acts as a recursion limit to end a boundary explicitly.",
			fill: "#FFFFFF",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Capability",
			acronym: "CAP",
			shape: "rounded box",
			icon: "spark",
			description: "Implementation-independent ability that satisfies requirements.",
			fill: "#052e16",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Class",
			acronym: "CLS",
			shape: "record",
			icon: "braces",
			description: "Represents a programming class.",
			fill: "#0f172a",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Component",
			acronym: "COM",
			shape: "box3d",
			icon: "cube",
			description: "Modular unit with a single responsibility and explicit interfaces.",
			fill: "#1e40af",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Condition",
			acronym: "CON",
			shape: "diamond",
			icon: "split",
			description: "Binary predicate influencing behavior.",
			fill: "#422006",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Constraint",
			acronym: "CNS",
			shape: "box",
			icon: "ruler",
			description: "Rule limiting allowable behavior or solutions.",
			fill: "#082f49",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Control",
			acronym: "CTL",
			shape: "octagon",
			icon: "lock",
			description: "Mechanism governing or constraining a process.",
			fill: "#713f12",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Data Store",
			acronym: "DTS",
			shape: "cylinder",
			icon: "database",
			description: "Persistent resource for durable storage/retrieval.",
			fill: "#075985",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Deployment",
			acronym: "DEP",
			shape: "box",
			icon: "cloud",
			description: "Defined environment or configuration where software executes.",
			fill: "#1e1b4b",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Driver",
			acronym: "DRI",
			shape: "rounded box",
			icon: "compass",
			description: "Motivation explaining why requirements exist.",
			fill: "#064e3b",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Event",
			acronym: "EVT",
			shape: "ellipse",
			icon: "bolt",
			description: "Discrete occurrence initiating a process or triggering behavior.",
			fill: "#5b21b6",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Feature",
			acronym: "FEA",
			shape: "box",
			icon: "star",
			description: "Externally observable behavior realizing one or more requirements.",
			fill: "#14532d",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Interface",
			acronym: "INT",
			shape: "note",
			icon: "plug",
			description: "Contract governing interaction across a boundary.",
			fill: "#102080",
			color: "#000000",
		},
		CardDefinition {
			card_type: "Mission",
			acronym: "MIS",
			shape: "double-octagon",
			icon: "target",
			description: "Root intent that spawns every downstream driver.",
			fill: "#022c22",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Node",
			acronym: "NOD",
			shape: "box",
			icon: "server",
			description: "Logical/physical execution environment hosting components or stores.",
			fill: "#312e81",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Node Instance",
			acronym: "NIN",
			shape: "box",
			icon: "server-cog",
			description: "Concrete runtime realization of a node.",
			fill: "#3730a3",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Note",
			acronym: "NOT",
			shape: "note",
			icon: "note-sticky",
			description: "Non-structural annotation attached to another element without a verb.",
			fill: "#1f2937",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Process",
			acronym: "PRO",
			shape: "box",
			icon: "workflow",
			description: "Ordered sequence of activities/decisions enabling a capability.",
			fill: "#2e1065",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Predicate",
			acronym: "PRD",
			shape: "diamond",
			icon: "function",
			description: "Logical statement evaluating to true/false in a state machine.",
			fill: "#581c87",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Activity",
			acronym: "ATV",
			shape: "rounded box",
			icon: "play-circle",
			description: "Discrete step within a process.",
			fill: "#4c1d95",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Requirement",
			acronym: "REQ",
			shape: "rounded box",
			icon: "checklist",
			description: "Verifiable statement of need/obligation.",
			fill: "#065f46",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Risk",
			acronym: "RIS",
			shape: "octagon",
			icon: "alert-triangle",
			description: "Potential for loss/harm from threats/vulnerabilities.",
			fill: "#881337",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "State",
			acronym: "STA",
			shape: "circle",
			icon: "dot",
			description: "Observable condition that persists until a transition.",
			fill: "#701a75",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "State Machine",
			acronym: "STM",
			shape: "octagon",
			icon: "timeline",
			description: "Behavioral model defining allowable states/transitions.",
			fill: "#4a044e",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Story",
			acronym: "STR",
			shape: "cds",
			icon: "book",
			description: "Narrative expressing desired behavior/outcome; should follow the “`As an ___ I want/need ___.`” format.",
			fill: "#365314",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "System",
			acronym: "SYS",
			shape: "folder",
			icon: "layers",
			description: "Bounded collection of interacting applications that fulfill a mission.",
			fill: "#172554",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Test",
			acronym: "TES",
			shape: "hexagon",
			icon: "beaker",
			description: "Procedure verifying that a feature satisfies requirements.",
			fill: "#022c22",
			color: "#FFFFFF",
		},
		CardDefinition {
			card_type: "Threat",
			acronym: "THR",
			shape: "octagon",
			icon: "bug",
			description: "Potential cause of an unwanted impact on the system/mission.",
			fill: "#4c0519",
			color: "#FFFFFF",
		},
	];

	const GROUPS: &[(&'static str, &[&'static str])] = &[
		("General", &["ACT", "DEP", "NOT"]),
		("Sepcial", &["NOT", "BND"]),
		(
			"Requirements",
			&["MIS", "DRI", "STR", "REQ", "CNS", "CAP", "ADR"],
		),
		("Process", &["PRO", "ATV", "CTL", "TRG", "CON"]),
		("State Machine", &["STM", "STA", "PRD", "EVT"]),
		(
			"System Structure",
			&[
				"SYS", "APP", "COM", "CLS", "INT", "DTS", "NOD", "NIN", "ART", "FEA", "TES",
			],
		),
		("Threat & Risk", &["THR", "RIS", "AST", "CTL"]),
		("Deployment", &["DEP", "NOD", "NIN"]),
	];
}
