pub struct ViewDefinition {
	pub name: &'static str,
	pub description: &'static str,
	pub root_card_types: &'static [&'static str],
	pub include_card_types: &'static [&'static str],
	pub optional_card_types: &'static [&'static str],
}

impl ViewDefinition {
	pub fn try_get_by_name(name: &str) -> Option<&'static ViewDefinition> {
		Self::DEFINITIONS.iter().find(|def| def.name == name)
	}

	pub fn get_all() -> &'static [ViewDefinition] {
		Self::DEFINITIONS
	}
}

impl ViewDefinition {
	const DEFINITIONS: &'static [ViewDefinition] = &[
		ViewDefinition {
			name: "Requirements",
			description: "Captures mission intent, motivation, and required capabilities, including architectural decisions that justify scope.",
			root_card_types: &["Mission"],
			include_card_types: &[
				"Mission",
				"Driver",
				"Capability",
				"Requirement",
				"ADR",
				"Boundary",
				"Note",
			],
			optional_card_types: &["Constraint", "Risk", "Story"],
		},
		ViewDefinition {
			name: "Use Case",
			description: "Describes externally visible behavior from the perspective of actors using narrative stories and constraints.",
			root_card_types: &["Actor"],
			include_card_types: &[
				"Actor",
				"Story",
				"Requirement",
				"Constraint",
				"Boundary",
				"Note",
			],
			optional_card_types: &["Capability", "Feature", "Risk"],
		},
		ViewDefinition {
			name: "Process",
			description: "Details how a capability is realized through ordered processes and activities with explicit triggering conditions.",
			root_card_types: &["Capability"],
			include_card_types: &[
				"Capability",
				"Process",
				"Activity",
				"Condition",
				"Trigger",
				"Boundary",
				"Note",
			],
			optional_card_types: &["Control", "Predicate"],
		},
		ViewDefinition {
			name: "Behavioral",
			description: "Models system behavior using state machines, states, predicates, and events without process contamination.",
			root_card_types: &["State Machine"],
			include_card_types: &[
				"State Machine",
				"State",
				"Predicate",
				"Event",
				"Boundary",
				"Note",
			],
			optional_card_types: &["Condition", "Control"],
		},
		ViewDefinition {
			name: "System Structure",
			description: "Shows the structural decomposition of the system into applications and components and their provided interfaces.",
			root_card_types: &["System"],
			include_card_types: &[
				"System",
				"Application",
				"Component",
				"Interface",
				"Data Store",
				"Artifact",
				"Feature",
				"Test",
				"Boundary",
				"Note",
			],
			optional_card_types: &["Class", "Capability"],
		},
		ViewDefinition {
			name: "Class",
			description: "Explains internal implementation structure, focusing on how applications and components are realized in code.",
			root_card_types: &["Application"],
			include_card_types: &[
				"Application",
				"Component",
				"Class",
				"Interface",
				"Data Store",
				"Artifact",
				"Feature",
				"Test",
				"Boundary",
				"Note",
			],
			optional_card_types: &["Constraint"],
		},
		ViewDefinition {
			name: "Deployment",
			description: "Defines where software executes, including environments, nodes, and relevant threats to deployed assets.",
			root_card_types: &["Deployment"],
			include_card_types: &[
				"Deployment",
				"Node",
				"Application",
				"Threat",
				"Boundary",
				"Note",
			],
			optional_card_types: &["Node Instance", "Component", "Data Store"],
		},
		ViewDefinition {
			name: "Runtime",
			description: "Describes concrete runtime realizations of nodes and the components executing within them.",
			root_card_types: &["Node Instance"],
			include_card_types: &["Node Instance", "Node", "Component", "Boundary", "Note"],
			optional_card_types: &["Application", "Control"],
		},
		ViewDefinition {
			name: "Security",
			description: "Analyzes protection of assets against threats, including actors, constraints, controls, and resulting risks.",
			root_card_types: &["Asset"],
			include_card_types: &[
				"Asset",
				"Threat",
				"Risk",
				"Control",
				"Constraint",
				"Actor",
				"Boundary",
				"Note",
			],
			optional_card_types: &["Component", "Interface"],
		},
		ViewDefinition {
			name: "Compliance Governance",
			description: "Demonstrates adherence to constraints through controls, risk treatment, and verifiable tests.",
			root_card_types: &["Requirement"],
			include_card_types: &[
				"Requirement",
				"Constraint",
				"Control",
				"Risk",
				"Test",
				"Boundary",
				"Note",
			],
			optional_card_types: &["ADR", "Process"],
		},
		ViewDefinition {
			name: "Traceability",
			description: "Provides end-to-end impact and coverage analysis from requirements through implementation and verification.",
			root_card_types: &["Requirement"],
			include_card_types: &[
				"Requirement",
				"Capability",
				"Feature",
				"Component",
				"Interface",
				"Test",
				"Constraint",
				"Control",
				"Risk",
				"Boundary",
				"Note",
			],
			optional_card_types: &[
				"Mission",
				"Driver",
				"Application",
				"Data Store",
				"Artifact",
				"Asset",
				"Threat",
				"Process",
				"Activity",
				"ADR",
				"Class",
			],
		},
		ViewDefinition {
			name: "Entire Model",
			description: "Displays the complete architectural model, highlighting shortest paths from the mission and alternate relationships.",
			root_card_types: &["Mission"],
			include_card_types: &[
				"Mission",
				"Driver",
				"Capability",
				"Requirement",
				"Feature",
				"System",
				"Application",
				"Component",
				"Interface",
				"Process",
				"Activity",
				"Condition",
				"Trigger",
				"State Machine",
				"State",
				"Predicate",
				"Event",
				"Deployment",
				"Node",
				"Node Instance",
				"Data Store",
				"Class",
				"Story",
				"Actor",
				"Constraint",
				"Control",
				"Risk",
				"Threat",
				"Asset",
				"Artifact",
				"Test",
				"ADR",
				"Boundary",
				"Note",
			],
			optional_card_types: &[],
		},
	];
}
